puts "The students of my cohort at Makers Academy"
puts "------------------------"
puts "Karin Nielson"
puts "Ben Hutchinson"
puts "Rich Lake"
puts "Yvette Cook"
puts "Denise Yu"
puts "Chris Handley"
puts "Victoria Stepanovna"
puts "Ella Schofield"
puts "Izzy Marwick"
puts "Nick Dyer"
puts "Alex Blease"
puts "Giorgia Amici"
puts "Chris Batte"
puts "Dale Stevens"
puts "Edward Byne"
puts "Tim Scully"
puts "Mischa I"
puts "Pavel Redics"
puts "Simon Lance"
puts "Clare Trembath"
puts "Ayo Obembe"
puts "Ben Conway"

print "Overall, we have "
print 22
puts " great students"

